### ISSUE TITLE
max function derivative

### ISSUE THREAD

**Issue by prangel-git** [wsmoses/Enzyme#101]
I've been playing around with Enzyme. Enzyme seems to be able to find the derivative of the following function just fine

double fun(double x) {
  if(x>=0) return x;
  return x * 0;
}

However, when I do "return 0" instead of "return x * 0", it calculates the derivative always equal to zero. I assumed that somehow the constant confuses the library, but the following functions finds the correct derivative:

double fun(double x) {
  if(x<=1) return x;
  return 1;
}

so, I guess it might be something to do with zero? I am not sure.

**Comment by wsmoses** [comment]
Mysterious, this definitely is a bug (and I've confirmed it locally). My guess is that activity analysis is being a bit too aggressive. I'll get back with a fix shortly.

**Comment by wsmoses** [comment]
It was indeed a slightly too aggressive activity analysis with a three line fix (https://github.com/wsmoses/Enzyme/pull/100/commits/2223fc1724182decaeb697636c1a2bda95ee6794).

Since there's pending CI changes in #100 I'm combining this into that PR (which will go in once reviewed).

**Comment by prangel-git** [comment]
Nice, thanks for the quick turn around.

Best!
