### ISSUE TITLE
Making a tag

### ISSUE THREAD

**Issue by nbren12** [wsmoses/Enzyme#119]
It takes a while to check out this repo, which is quite large. Uncompressed the repo size is 2 GB, which makes it a bit slow to build dockerfiles with. To cut down on the initial download for users, it would be nice to distribute tarballs with either
1. the full working tree (but no .git) (273 MB).
2. the enzyme subdirectory (161 MB).
3. the enzyme subdirectory but no benchmark data (748 kb)

This last option is orders of magnitudes smaller, so would be awesome. With some small configurations this github repo can produce such an archive for every git tag. Just add this to the .gitattributes:
```
/LICENSE export-ignore
/Readme.md export-ignore
/clang export-ignore
/clang-tools-extra export-ignore
/compiler-rt export-ignore
/contrib export-ignore
/debuginfo-tests export-ignore
/libcxx export-ignore
/libcxxabi export-ignore
/libunwind export-ignore
/lld export-ignore
/lldb export-ignore
/llvm export-ignore
/openmp export-ignore
/polly export-ignore
/tests export-ignore
/enzyme/benchmarks export-ignore
```
and push a tag to github
```
git tag v0.1.0
git push --tags origin
```

The benchmarks build would also need to be made an optional part of the `CMakeLists` for this to work.

**Comment by wsmoses** [comment]
This is a good idea and seems reasonable to me!

Would you be able to make a PR with the git attributes?

I may wait to make the tag until we've finished merging in all of the updates from the fortran branch

**Comment by nbren12** [comment]
> Would you be able to make a PR with the git attributes?

Sure. See #131.

> I may wait to make the tag until we've finished merging in all of the updates from the fortran branch

Sounds good.

**Comment by vchuravy** [comment]
https://github.com/wsmoses/Enzyme/releases/tag/v0.0.7  is ~800kb!
