### ISSUE TITLE
Quadratic memory usage

### ISSUE THREAD

**Issue by unrealwill** [wsmoses/Enzyme#122]
Hello, I'm still learning Enzyme.
I was expecting the following simple code to not require quadratic memory for the backward pass with enzyme

`test2.cpp`
```
#include <stdio.h>
#include <iostream>
#include <stdlib.h>
#include <random>

void foo(double* parts, double *x_out,int n) {
    int d = 3;
    *x_out = 0.0;

    for( int i = 0 ; i < n ; i++)
    {
        for( int j = 0 ; j < n ; j++)
        {
            for( int k = 0 ; k < d ; k++)
            {
                double temp = parts[d*i+k]-parts[d*j+k];
                *x_out += temp*temp;
            }
        }
    }
}


int enzyme_dup;
int enzyme_out;
int enzyme_const;

typedef void (*f_ptr)(double*, double*,int);

extern void __enzyme_autodiff(f_ptr,
    int, double*, double*,
    int, double*, double*,
    int, int);


int main() {

    srand(42);

    std::mt19937 e2(42);
    std::uniform_real_distribution<> dist(0, 10);
    int n = 100000;
    int d = 3;
    double* x = new double[n*d];
    double* d_x = new double[n*d];
    for( int i = 0 ; i < n*d ; i++)
    {
        x[i] = dist(e2);
        d_x[i] = 0.0;
    }

    double y;
    double d_y = 1.0;

    printf("before autodiff\n");
    __enzyme_autodiff(foo,
        enzyme_dup, x, d_x,
        enzyme_dup, &y, &d_y,
        enzyme_const, n);


    printf("%f \n", y);
    for( int i = 0 ; i < 100 ; i++)
    {
    printf("dx[%d] = %f\n",i, d_x[i]);
    }

}
```
I used the one liner to compile, ( I also tried to emit O2 llvm and opt it but same results )
`clang test2.cpp -lstdc++ -lm -Xclang  -load -Xclang /usr/local/lib/ClangEnzyme-7.so -o test2`

It crashes with SegFault probably because it tries to allocate (or stack-allocate)
```
before autodiff
Segmentation fault (core dumped)
```

Can you please advise ?
Thanks

**Comment by wsmoses** [comment]
Having not tried out your code, my immediate guess what's happening is that because `parts` and `x_out` aren't marked restrict (or noalias) the compiler has to assume that they could overlap and thus it has to cache a bunch.

Try marking the two arguments as restrict. With good Alias Analysis markings I think this code shouldn't require _any_ extra memory in cache.

**Comment by unrealwill** [comment]
Thanks :+1: 
By replacing the declaration to use restrict with : 
`void foo( double* __restrict__ parts, double * __restrict__ x_out,int n)`

Now it works fine !
