### ISSUE TITLE
FNeg in ForwardMode

### ISSUE THREAD

**Issue by mtowara** [wsmoses/Enzyme#230]
Hi,
the implementation of unary minus for ForwardMode seems to be broken.
I'm using the current brew version (LLVM 12) on Linux and opt produces a segfault.
I traced the error to
https://github.com/wsmoses/Enzyme/blob/9be50337dbf98a6a0489e94660d15586466a4b34/enzyme/Enzyme/AdjointGenerator.h#L252
where it tries to get a ReverseBuilder which I suppose doesn't exist in ForwardMode.
But I'm not sure how to procede from there.

Testcase to reproduce:
```
// clang++ fneg.cpp -S -emit-llvm -o input.ll -O2 -fno-vectorize -fno-slp-vectorize -fno-unroll-loops
// opt input.ll -load=/home/linuxbrew/.linuxbrew/lib/LLVMEnzyme-12.so -enzyme -o output.ll -S
// clang++ -c output.ll

extern double __enzyme_fwddiff(void*, double, double);

double foo(double x){
    return -x;
}

double dfoo(double x){
    return __enzyme_fwddiff((void*)foo, x, 1.0);
}
```

Best
Markus

**Comment by vchuravy** [comment]
Thank you for the report. Forward mode is currently heavily under development and I would recommend using reverse mode until full coverage has been reached.
