### ISSUE TITLE
Compilation fail when printf strings of length 1

### ISSUE THREAD

**Issue by unrealwill** [wsmoses/Enzyme#240]
Hello,

The compilation fails when using printf of strings of length 1 inside the function that is differentiated when it has been wrapped.

Clang version 11.1.0
Enzyme recent from a few days. ae09f3d45f3680121a781ebc2ae5fc7a52478863

`bugprintf.cpp`
```
#include <iostream>

using namespace std;

int enzyme_dup;
void __enzyme_autodiff(...);

template <typename T>
void compute( double* x, double* out );

template< typename T>
void compute( double* x, double* out)
{
    T::comp(x,out);
}

template<typename T>
void compute_d(double* x, double* res)
{
  double out = 0.0;
  double dout = 1.0;
    __enzyme_autodiff(compute<T >,
                                        enzyme_dup, x,res,
                                        enzyme_dup,&out,&dout);

}

template<typename T>
class D
{
public:
  D()
  {}

  static void comp(double* v, double* out )
  {
      compute_d< T >(v,out);
  }
};

class Fun2{};
template<>
void compute<Fun2>( double* x, double* out )
{
  printf("a");// single character string make the compiler crash
  printf("ab");//but multi character printf work fine
  *out = 3*x[0] * x[0] ;
}

int main(int argc, char** argv )
{
  cout<<"bug printf "<<endl;
  const int d = 1;
  double* x = new double[d] ;
  x[0] = 5.0;

  //Make the compiler crash when a single character printf is present above
  double g=0.0;
  D<Fun2>::comp(x, &g);
  cout << "g " << g << endl ;
}

```

Compilation with : 
`clang bugprintf.cpp -lstdc++ -lm -Xclang -load -Xclang /usr/local/lib/ClangEnzyme-11.so  -O2  -o bugprintf -fno-exceptions
`

Here is the output of the compilation : (as a file to keep the thread readable)
[bugprintf.log](https://github.com/wsmoses/Enzyme/files/6858967/bugprintf.log)

**Comment by wsmoses** [comment]
Happily this is a 10 second fix that will go in once the above PR has it's checks pass.

**Comment by unrealwill** [comment]
Thanks ! :+1: 
I don't know how hard it is, but if it's not too hard would it be possible to make iostream std::cout available too.

**Comment by wsmoses** [comment]
Yeah for sure, I'll make a PR for that in a bit.
