### ISSUE TITLE
Compilation Fail : "could not deduce type of integer" when copying stack variables

### ISSUE THREAD

**Issue by unrealwill** [wsmoses/Enzyme#304]
Hello, 

Here is a simple case that result in a type analysis bug.

` bugPadding.cpp`
```
#include <iostream>
#include <math.h>
#include <cstdint>
#include <string>
using namespace std;

extern int enzyme_dup;
extern int enzyme_dupnoneed;
extern int enzyme_out;
extern int enzyme_const;

void __enzyme_autodiff(...);

inline void zero( double*__restrict__ v, int n)
{
  for( int i = 0 ; i < n ; i++) v[i] = 0.0;
}

inline void printRowVector( double* x, int n )
{
    for( int i = 0 ; i < n ; i++)
    {
      cout << x[i] << " ";
    }
    cout << endl;
}

void myopfun( double*__restrict__ M, double*__restrict__ out )
{
  for( int i = 0 ; i<2 ; i++)
      for( int j = 0 ; j < 32 ; j++)
            out[32*i+j] = M[32*i+j]; //This works when you remove the + j either in out or M
}

void distanceToTarget( double* param, double* out)
{
    double message[512];
    for( int i = 0; i < 512 ; i++)
        message[i] = param[i];

    double feat[256]; zero(feat,256);
    myopfun( message ,feat );

    for( int i = 0; i < 256 ; i++)
        *out += feat[i]*feat[i];

}

int main()
{
  const int paramSize = 512; 
  double param[ paramSize ];
  zero(param,paramSize);
  double dparam[ paramSize ];

  double loss = 0.0;
  distanceToTarget( param, &loss);

  cout << "distanceToTarget " << loss << endl;
  zero(dparam,paramSize);
  loss = 0.0;
  double dloss = 1.0;

  __enzyme_autodiff( distanceToTarget, enzyme_dup, param,dparam,
                                                                enzyme_dup, &loss,&dloss);
  cout << "dparam " << endl;
  printRowVector( dparam, paramSize);

}
```
Compilation with : 		
`clang bugPadding.cpp -lstdc++ -lm -Rpass=enzyme -Xclang -load -Xclang /usr/local/lib/ClangEnzyme-12.so  -O2 -mllvm -enzyme-globals-default-inactive=1 -o bin/bugPadding -fno-exceptions
`
Relevant extract : 
```
could not deduce type of integer   %scevgep22.1.i = bitcast double* %scevgep.1.i to i8* num:256 q:{[]:Pointer} 
warning: failed to deduce type of value   %scevgep22.1.i = bitcast double* %scevgep.1.i to i8* [-Wpass-failed=enzyme]
clang-12: ../Enzyme/TypeAnalysis/TypeAnalysis.cpp:4318: ConcreteType TypeAnalysis::firstPointer(size_t, llvm::Value*, const FnTypeInfo&, bool, bool): Assertion `0 && "could not deduce type of integer"' failed.

```

Full log:
[bugPadding.log](https://github.com/wsmoses/Enzyme/files/6999759/bugPadding.log)

**Comment by wsmoses** [comment]
So this appears not to be a bug within Enzyme so much as it is LLVM not keeping TBAA. Enzyme needs to know the types of loads/stores to be able to correctly differentiate. These are added automatically by the Clang front end. Without optimization, the loop nest within myopfun are literal loads and stores, with that information. At a higher optimization level LLVM transforms that into a memcpy, but doesn't persist the type metadata. The correct solution here is for LLVM upstream to keep the type metadata when it does that pass (which I can take a look at).

Alternatively, you can explore the use of the -enzyme-loose-types flag, which tells Enzyme to make it's best guess when it cannot determine the type of something.

**Comment by wsmoses** [comment]
Upstream PR opened here: https://reviews.llvm.org/D108221

**Comment by unrealwill** [comment]
Cool :) 
Passing  `-mllvm -enzyme-loose-types` to the compilation did the trick and the compilation no longer fails, even on a huge graph.

Thanks again !
