### ISSUE TITLE
Compatibility with LLVM main stream

### ISSUE THREAD

**Issue by cookieli** [wsmoses/Enzyme#359]
I built Enzyme with llvm main strem, which trigers following problem:
file failed to open for reading (No such file or directory):
llvm-project/llvm/include/llvm/Transforms/Utils/ScalarEvolutionExpander.h
And i can't find this file in llvm project main stream

**Comment by wsmoses** [comment]
Can you paste the output of cmake?

**Comment by cookieli** [comment]
(base) lzx@lzx-XPS-13-9360:~/Enzyme/enzyme/build$ cmake -G Ninja .. -DLLVM_DIR= ../../../llvm-project/build/lib/cmake/llvm 

-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
LLVM_SHLIBEXT=.so
found llvm dir /home/lzx/Enzyme/enzyme/build
found llvm lit /home/lzx/Enzyme/enzyme/build
CMAKE_PREFIX_PATH /home/lzx/Enzyme/enzyme/build
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Linker detection: GNU ld
LLVM_INSTALL_PREFIX: /usr/local
LLVM_INCLUDE_DIRS: /usr/local/include
found llvm definitions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
found llvm version 12
first llvm include directory/usr/local/include
found bench flags: -I/home/lzx/Enzyme/enzyme/build/benchmarks/adept2/src/adept2/include -I/home/lzx/Enzyme/enzyme/build/benchmarks/tapenade/src/tapenade
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lzx/Enzyme/enzyme/build

Here's first part of llvm

**Comment by cookieli** [comment]
Thank you, it worked!!
