### ISSUE TITLE
LLVM build does not prefix libraries on Linux

### ISSUE THREAD

**Issue by bytesnake** [wsmoses/Enzyme#94]
I had to do some gymnastics with the linker to find enzyme in the system search path. I don't know much about the LLVM build system, but 
```
if (UNIX)
    set(CMAKE_SHARED_LIBRARY_PREFIX "lib")
endif()   
```
had no effect.

**Comment by wsmoses** [comment]
Started looking into this but then got sidetracked.

I want to confirm what LLVM's convention is for naming these sorts of libraries internally, but it shouldn't be hard to modify the create llvm library builder to give this a more standard name.

**Comment by bytesnake** [comment]
the only nuisance is that the user has to copy it manually to `libenzyme.so` right now when using enzyme as a system library and not compiling it in the build script

**Comment by wsmoses** [comment]
So I checked and it does appear that the standard convention within LLVM for these sorts of libraries (usually intended to be dynamically loaded into clang/opt) is to not prefix it. That said, I think a symlink from LLVMEnzyme-X.so to libenzyme-X.so would work here, no?

Also fwiw, I think it's also possible to manually specify a library with l:path/to/library if that makes it easier til we add the symlink.

**Comment by bytesnake** [comment]
yep prefixing with `:` can be used to disable lib prefixing.
